services:
  postgres:
    image: postgres:16
    container_name: herobrine_postgres

    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_DB: herobrine_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    restart: unless-stopped

volumes:
  pgdata: # Volume for PostgreSQL data persistence